name: Bash Script Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Bash
      run: |
        sudo apt update
        sudo apt install -y bash

    - name: Run Bash script tests
      run: |
        find . -type f -name "*.sh" -exec bash -n {} \;
